general cleanup, basic io api creation
JGoard/JOCKTOS pull request #30
Opened 2024-08-18 14:51 UTC by JGoard

- Ability to initialize dig i/o on the fly and to get/set bits with basic error-checking/handling
- Added intermediary prefixes for jock_os_xxx or jock_io_xxx
- Removed critical sections macro in favor of function calls
- Added low-power mode idle task
- openOCD flashing supported by docker container now. Still need to add GDB interface with VSCode

2024-08-19 18:29 UTC, nick-a-schneider requested changes
There are a couple different variable name formats, I believe we settled on snake_case for variables and camelCase for functions. Would you prefer to switch these? Its looking like with the prefixes, snake_case would be better for functions, and most of the new variables here are camelCase.

Could we prioritize getting the io+sys changes merged, and hold off on the usbipd stuff until the integrated debugging can use the containers openocd? I'm having to plug cycle and reload the window every time I attach the debugger

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/inc/os.h
> +void jock_os_switchRunningTask(volatile TaskControlBlock** head);
switch running task shouldn't be in the user API. We will want it for internal use outside `os.h` (i..e `syncro.h`), but I don't think the user API prefix is correct for that

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/inc/os.h
> +void jock_os_configureJOCKTOS(JocktosConfig* config);
The `JOCKTOS` suffix is redundant

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/inc/os.h
> +void jock_os_runJOCKTOS(void);
The `JOCKTOS` suffix is redundant

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/os.c
> +    uint32_t  primask = 0;
rather than passing `primask` around between the enter and exit methods can't we use a volatile global?

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/os.c
> +    uint32_t primask;
needs commented out

2024-08-19 18:29 UTC, nick-a-schneider commented on Dockerfile
> +    udev \
duplicate

2024-08-19 18:29 UTC, nick-a-schneider commented on Dockerfile
> +    git
lines 15-19 are duplicates

2024-08-19 18:29 UTC, nick-a-schneider commented on Dockerfile
> +libusb-1.0-0 \
Do we need all of these libusb versions? 
0.1-4, 1.0-0, 1.0-0-dev, and -dev

2024-08-19 18:29 UTC, nick-a-schneider commented on Dockerfile
> +# install make and cmake build dependancies
lets separate out the make / cmake deps from the containerized USB deps

2024-08-19 18:29 UTC, nick-a-schneider commented on Dockerfile
> +#build and install OPENOCD from repository
If this is an old abandoned approach it should be removed, otherwise some clear TODO

2024-08-19 18:29 UTC, nick-a-schneider commented on .vscode/tasks.json
> +      "label": "Bind OpenOCD",
This label is kinda misleading, maybe "Bind USB Device"?

2024-08-19 18:29 UTC, nick-a-schneider commented on .vscode/tasks.json
> +        "--wsl","Ubuntu",
The "Ubuntu" arg is optional, and since mine are named with the versions causes this task to fail on my end, works fine without it though

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/main.c
> +#include "stm32m4cortex_bsp.h"
The user should only have to include `jocktos.h` to get all of this

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/main.c
> +    uint8_t DigInvalue = 0;
PascalCase variable

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/sys.c
> +    static uint32_t currentTime = 0;
over indent

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/sys.c
> +    static uint32_t previousTime= 0;
camelCase variable

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/os.c
> +      if (irq_flag == 0) {
The indentation for the if block is off

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/io.c
> +
No return values

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/io.c
> +    uint32_t digitalInVals = port->IDR;
What is the variable for?

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/io.c
> +    if (pin > PIN_MAX || pin < 0 || port == NULL || value == NULL){
pin < 0 is irrelevant since pin is unsigned
(this happens in a couple places)

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/inc/io.h
> +int16_t jock_io_setDigitalOutput    (GPIO_TypeDef *port, uint8_t pin, uint8_t value);
missing docstrings

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/main.c
> +#include "stm32m4cortex_bsp.h"
Also needs sys.h for `jock_sys_LEDInit`

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/main.c
> +        jock_io_setDigitalOutput(GPIOB, 3, value);
We should either use the return values our explicitly discard them  
`(void)jock_io_setDigitalOutput(GPIOB, 3, value);`

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/io.c
> +    if (pin > PIN_MAX || pin < 0 || port == NULL || value == NULL){
Why is `value` 8bit unsigned instead of bool? I get they're still the same size, but using bool would be easier to read and give us type warning at compile time. 
Along these lines, `value == NULL` is true when value is zero / false, so this function can only set outputs high

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/src/os.c
> +void idleJOCKTOS(void* arg);
Since these functions cycle through the tasks queue rather than being called explicitly from the kernel I think the suffix `Task` was more appropriate than `JOCKTOS`

2024-08-19 18:29 UTC, nick-a-schneider commented on .vscode/tasks.json
> +}
The statusbar is getting really cluttered. Can we hide the `Bind` and `Dock` tasks, and make a dependency chain for for the docker flash task?

2024-08-19 18:29 UTC, nick-a-schneider commented on jocktos/inc/io.h
> +#define JOCK_IO_OTYPE_OD    0b01    // 10 MHz
Can we use enums instead of just macros for these?

2024-08-19 18:39 UTC, nick-a-schneider commented on jocktos/src/io.c
> +#define PIN_MAX 15 // 15 pins per GPIO
This macro should probably be in the bsp instead of here

2024-08-19 19:05 UTC, JGoard commented on jocktos/inc/os.h
> +void jock_os_switchRunningTask(volatile TaskControlBlock** head);
will do

2024-08-19 19:17 UTC, JGoard commented
I think snake_case for functions maybe better and variables should be camelCase. I was trying to keep it consistent with the functions, but the prefixes look better imo with snake case. I can work on making these changes to os, sys, and io

2024-08-19 19:18 UTC, JGoard commented
I will be out of town this week, so whenever I have downtime I will try and fix these

2024-08-19 19:29 UTC, JGoard commented
For the openOCD debugger, I have just gone back to flashing and debugging locally for now until it gets sorted out. I encountered the pain of binding and flashing then unpluggin to debug

2024-09-03 19:37 UTC, nick-a-schneider commented on Dockerfile
> +RUN git clone https://github.com/JGoard/jocktos.git && cd ..
This isn't doing anything, the container is already mounted to the hosts workspace folder

2024-09-03 19:38 UTC, nick-a-schneider commented on .vscode/c_cpp_properties.json
> +            "compilerPath": "${env:ARMGCC_DIR}/arm-none-eabi-gcc",
This doesn't work in the container

2024-12-06 23:56 UTC, merged